// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:97a63570-25cd-4f43-af63-e31bdf2a04b0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vCK3NUszh",
    "aws_user_pools_web_client_id": "pnjnvcqu5j5p1r14as7ie1hch"
};


export default awsmobile;
